// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getAccessToken } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
//
// Uses getAccessToken() (cached) NOT supabase.auth.getSession(): this runs on every
// serverFn RPC, and getSession() refreshes-on-read against the DEVICE clock, so on a
// fast clock this path was the engine of the refresh storm (see client.ts header).
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const token = await getAccessToken()
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
